version: '3'

tasks:
  pack:
    desc: Pack the tool into a local NuGet package for testing
    cmds:
      - echo "Packing tool locally for testing..."
      - cd src/McpClient
      - dotnet pack --configuration Debug --output ./nupkg

  install:
    desc: Install the tool globally from the locally packed NuGet package
    deps: [pack]
    cmds:
      - echo "Uninstalling the existing global version of the tool (if any)..."
      - dotnet tool uninstall --global bjornkpu.ai
      - echo "Installing the tool from the local package..."
      - dotnet tool install --global --add-source ./nupkg bjornkpu.ai

  uninstall:
    desc: Uninstall the tool globally
    cmds:
      - echo "Uninstalling the globally installed tool..."
      - dotnet tool uninstall --global bjornkpu.ai
