name: Release .NET Tool

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x' # Adjust based on your .NET version

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Extract version from Git tag
      - name: Extract version from tag
        id: get_version
        run: echo "PACKAGE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      # Pack the tool
      - name: Pack NuGet package
        run: dotnet pack --configuration Release /p:PackageVersion=${{ env.PACKAGE_VERSION }}

      # Publish to NuGet
      - name: Push package to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json